export const list = [
    {
        "c_state": 0,
        "display": "Luxury",
        "icon": "null",
        "id": 12,
        "passenger_count": "4",
        "r_state": 1,
        "t_state": 0,
        "type": "Luxury",
        "updated_at": "Sun, 26 Mar 2023 10:29:43 GMT",
        "w_state": 1
    },
    {
        "c_state": 0,
        "display": "SUV",
        "icon": "null",
        "id": 9,
        "passenger_count": "2",
        "r_state": 1,
        "t_state": 0,
        "type": "SUV",
        "updated_at": "Fri, 18 Nov 2022 08:28:46 GMT",
        "w_state": 1
    },
    {
        "c_state": 0,
        "display": "Hatchback",
        "icon": "null",
        "id": 10,
        "passenger_count": "4",
        "r_state": 1,
        "t_state": 0,
        "type": "Hatchback",
        "updated_at": "Thu, 17 Nov 2022 13:09:41 GMT",
        "w_state": 0
    },
    {
        "c_state": 1,
        "display": "Sedan Car",
        "icon": "null",
        "id": 3,
        "passenger_count": "3",
        "r_state": 1,
        "t_state": 0,
        "type": "Sedan Car",
        "updated_at": "Thu, 17 Nov 2022 13:08:29 GMT",
        "w_state": 1
    },
    {
        "c_state": 1,
        "display": "Van",
        "icon": "null",
        "id": 5,
        "passenger_count": "10",
        "r_state": 1,
        "t_state": 0,
        "type": "Van",
        "updated_at": "Thu, 17 Nov 2022 10:50:34 GMT",
        "w_state": 0
    },
    {
        "c_state": 1,
        "display": "Mini Van",
        "icon": "null",
        "id": 4,
        "passenger_count": "6",
        "r_state": 1,
        "t_state": 0,
        "type": "Mini Van",
        "updated_at": "Thu, 17 Nov 2022 10:50:20 GMT",
        "w_state": 0
    }
]

export const rentPackges = [
    {
        "d_range_begin": 7500,
        "d_range_end": 10000,
        "display": "Mini Van",
        "id": 6,
        "m_range_begin": 150000,
        "m_range_end": 200000
    },
    {
        "d_range_begin": 12000,
        "d_range_end": 15000,
        "display": "Van",
        "id": 5,
        "m_range_begin": 220000,
        "m_range_end": 280000
    },
    {
        "d_range_begin": 7500,
        "d_range_end": 10000,
        "display": "Sedan",
        "id": 4,
        "m_range_begin": 150000,
        "m_range_end": 200000
    },
    {
        "d_range_begin": 22000,
        "d_range_end": 25000,
        "display": "Luxury",
        "id": 3,
        "m_range_begin": 350000,
        "m_range_end": 400000
    },
    {
        "d_range_begin": 12000,
        "d_range_end": 15000,
        "display": "SUV",
        "id": 2,
        "m_range_begin": 220000,
        "m_range_end": 280000
    },
    {
        "d_range_begin": 4500,
        "d_range_end": 7000,
        "display": "Hatchback",
        "id": 1,
        "m_range_begin": 70000,
        "m_range_end": 140000
    }
]

export const rentSet = [
    {
        "c_state": 0,
        "cover": "https://viptravels.lk/public/images/gallery/model-covers/kdhhighroof.jpg",
        "created_at": "Mon, 27 Mar 2023 15:04:10 GMT",
        "deleted_at": null,
        "display_vehicle_type": "Van",
        "engine_capacity": 1000,
        "fuel_type": 1,
        "id": 30,
        "model": "Toyota KDH Highroof",
        "note": null,
        "passenger_count": "10",
        "r_package": 5,
        "r_state": 1,
        "rating_date": "0, 0",
        "ratings": 0.0,
        "transmission": 0,
        "trim_edition": "",
        "updated_at": "Mon, 27 Mar 2023 15:24:10 GMT",
        "vehicle_type": 5,
        "w_package": 2,
        "w_state": 0
    },
    {
        "c_state": 0,
        "cover": "https://viptravels.lk/public/images/gallery/model-covers/caravan.jpg",
        "created_at": "Mon, 27 Mar 2023 15:02:27 GMT",
        "deleted_at": null,
        "display_vehicle_type": "Van",
        "engine_capacity": 1000,
        "fuel_type": 1,
        "id": 28,
        "model": "Nissan Caravan",
        "note": null,
        "passenger_count": "10",
        "r_package": 5,
        "r_state": 1,
        "rating_date": "0, 0",
        "ratings": 0.0,
        "transmission": 1,
        "trim_edition": "",
        "updated_at": "Mon, 27 Mar 2023 15:24:07 GMT",
        "vehicle_type": 5,
        "w_package": 2,
        "w_state": 0
    },
    {
        "c_state": 0,
        "cover": "https://viptravels.lk/public/images/gallery/model-covers/kdhnormal.jpg",
        "created_at": "Mon, 27 Mar 2023 15:03:20 GMT",
        "deleted_at": null,
        "display_vehicle_type": "Van",
        "engine_capacity": 1000,
        "fuel_type": 0,
        "id": 29,
        "model": "Toyota KDH",
        "note": null,
        "passenger_count": "10",
        "r_package": 5,
        "r_state": 1,
        "rating_date": "0, 0",
        "ratings": 0.0,
        "transmission": 0,
        "trim_edition": "",
        "updated_at": "Mon, 27 Mar 2023 15:24:07 GMT",
        "vehicle_type": 5,
        "w_package": 2,
        "w_state": 0
    },
    {
        "c_state": 0,
        "cover": "https://viptravels.lk/public/images/gallery/model-covers/vannet.jpg",
        "created_at": "Mon, 27 Mar 2023 15:01:22 GMT",
        "deleted_at": null,
        "display_vehicle_type": "Mini Van",
        "engine_capacity": 1000,
        "fuel_type": 1,
        "id": 27,
        "model": "Nissan Vannet",
        "note": null,
        "passenger_count": "6",
        "r_package": 6,
        "r_state": 1,
        "rating_date": "0, 0",
        "ratings": 0.0,
        "transmission": 1,
        "trim_edition": "",
        "updated_at": "Mon, 27 Mar 2023 15:24:05 GMT",
        "vehicle_type": 4,
        "w_package": 2,
        "w_state": 0
    },
    {
        "c_state": 0,
        "cover": "https://viptravels.lk/public/images/gallery/model-covers/noah.jpg",
        "created_at": "Mon, 27 Mar 2023 14:59:14 GMT",
        "deleted_at": null,
        "display_vehicle_type": "Mini Van",
        "engine_capacity": 1000,
        "fuel_type": 1,
        "id": 25,
        "model": "Toyota Noah",
        "note": null,
        "passenger_count": "6",
        "r_package": 6,
        "r_state": 1,
        "rating_date": "0, 0",
        "ratings": 0.0,
        "transmission": 0,
        "trim_edition": "",
        "updated_at": "Mon, 27 Mar 2023 15:24:04 GMT",
        "vehicle_type": 4,
        "w_package": 2,
        "w_state": 0
    },
    {
        "c_state": 0,
        "cover": "https://viptravels.lk/public/images/gallery/model-covers/suzukievery.jpg",
        "created_at": "Mon, 27 Mar 2023 15:00:20 GMT",
        "deleted_at": null,
        "display_vehicle_type": "Mini Van",
        "engine_capacity": 1000,
        "fuel_type": 0,
        "id": 26,
        "model": "Suzuki Every",
        "note": null,
        "passenger_count": "6",
        "r_package": 6,
        "r_state": 1,
        "rating_date": "0, 0",
        "ratings": 0.0,
        "transmission": 0,
        "trim_edition": "",
        "updated_at": "Mon, 27 Mar 2023 15:24:04 GMT",
        "vehicle_type": 4,
        "w_package": 2,
        "w_state": 0
    },
    {
        "c_state": 0,
        "cover": "https://viptravels.lk/public/images/gallery/model-covers/jaguarxf.jpg",
        "created_at": "Mon, 27 Mar 2023 08:05:23 GMT",
        "deleted_at": null,
        "display_vehicle_type": "Luxury",
        "engine_capacity": 1997,
        "fuel_type": 0,
        "id": 8,
        "model": "Jaguar XF",
        "note": null,
        "passenger_count": "4",
        "r_package": 3,
        "r_state": 1,
        "rating_date": "0, 0",
        "ratings": 0.0,
        "transmission": 0,
        "trim_edition": "",
        "updated_at": "Mon, 27 Mar 2023 14:16:01 GMT",
        "vehicle_type": 12,
        "w_package": 1,
        "w_state": 1
    },
    {
        "c_state": 0,
        "cover": "https://viptravels.lk/public/images/gallery/model-covers/civic.jpg",
        "created_at": "Mon, 27 Mar 2023 12:51:01 GMT",
        "deleted_at": null,
        "display_vehicle_type": "Sedan Car",
        "engine_capacity": 1000,
        "fuel_type": 0,
        "id": 21,
        "model": "Honda Civic",
        "note": null,
        "passenger_count": "3",
        "r_package": 4,
        "r_state": 1,
        "rating_date": "0, 0",
        "ratings": 0.0,
        "transmission": 0,
        "trim_edition": "",
        "updated_at": "Mon, 27 Mar 2023 14:09:03 GMT",
        "vehicle_type": 3,
        "w_package": 2,
        "w_state": 0
    },
    {
        "c_state": 0,
        "cover": "https://viptravels.lk/public/images/gallery/model-covers/allion.jpg",
        "created_at": "Mon, 27 Mar 2023 11:46:47 GMT",
        "deleted_at": null,
        "display_vehicle_type": "Sedan Car",
        "engine_capacity": 1000,
        "fuel_type": 0,
        "id": 18,
        "model": "Toyota Allion",
        "note": null,
        "passenger_count": "3",
        "r_package": 4,
        "r_state": 1,
        "rating_date": "0, 0",
        "ratings": 0.0,
        "transmission": 0,
        "trim_edition": "",
        "updated_at": "Mon, 27 Mar 2023 14:08:37 GMT",
        "vehicle_type": 3,
        "w_package": 2,
        "w_state": 1
    },
    {
        "c_state": 0,
        "cover": "https://viptravels.lk/public/images/gallery/model-covers/grace.jpg",
        "created_at": "Mon, 27 Mar 2023 13:22:24 GMT",
        "deleted_at": null,
        "display_vehicle_type": "Sedan Car",
        "engine_capacity": 1000,
        "fuel_type": 0,
        "id": 22,
        "model": "Honda Grace",
        "note": null,
        "passenger_count": "3",
        "r_package": 4,
        "r_state": 1,
        "rating_date": "0, 0",
        "ratings": 0.0,
        "transmission": 0,
        "trim_edition": "",
        "updated_at": "Mon, 27 Mar 2023 14:08:27 GMT",
        "vehicle_type": 3,
        "w_package": 2,
        "w_state": 1
    },
    {
        "c_state": 0,
        "cover": "https://viptravels.lk/public/images/gallery/model-covers/premio.jpg",
        "created_at": "Mon, 27 Mar 2023 13:25:08 GMT",
        "deleted_at": null,
        "display_vehicle_type": "Sedan Car",
        "engine_capacity": 1000,
        "fuel_type": 0,
        "id": 23,
        "model": "Toyota Premio",
        "note": null,
        "passenger_count": "3",
        "r_package": 4,
        "r_state": 1,
        "rating_date": "0, 0",
        "ratings": 0.0,
        "transmission": 0,
        "trim_edition": "",
        "updated_at": "Mon, 27 Mar 2023 14:08:25 GMT",
        "vehicle_type": 3,
        "w_package": 2,
        "w_state": 1
    },
    {
        "c_state": 0,
        "cover": "https://viptravels.lk/public/images/gallery/model-covers/axio.jpg",
        "created_at": "Mon, 27 Mar 2023 13:26:00 GMT",
        "deleted_at": null,
        "display_vehicle_type": "Sedan Car",
        "engine_capacity": 1000,
        "fuel_type": 0,
        "id": 24,
        "model": "Toyota Axio",
        "note": null,
        "passenger_count": "3",
        "r_package": 4,
        "r_state": 1,
        "rating_date": "0, 0",
        "ratings": 0.0,
        "transmission": 0,
        "trim_edition": "",
        "updated_at": "Mon, 27 Mar 2023 14:08:24 GMT",
        "vehicle_type": 3,
        "w_package": 2,
        "w_state": 1
    },
    {
        "c_state": 0,
        "cover": "https://viptravels.lk/public/images/gallery/model-covers/priuse.jpg",
        "created_at": "Mon, 27 Mar 2023 11:45:50 GMT",
        "deleted_at": null,
        "display_vehicle_type": "Sedan Car",
        "engine_capacity": 1000,
        "fuel_type": 0,
        "id": 17,
        "model": "Toyota Priuse",
        "note": null,
        "passenger_count": "3",
        "r_package": 4,
        "r_state": 1,
        "rating_date": "0, 0",
        "ratings": 0.0,
        "transmission": 0,
        "trim_edition": "",
        "updated_at": "Mon, 27 Mar 2023 14:08:20 GMT",
        "vehicle_type": 3,
        "w_package": 2,
        "w_state": 1
    },
    {
        "c_state": 0,
        "cover": "https://viptravels.lk/public/images/gallery/model-covers/mitsubishioutlander.jpg",
        "created_at": "Mon, 27 Mar 2023 07:10:06 GMT",
        "deleted_at": null,
        "display_vehicle_type": "SUV",
        "engine_capacity": 2360,
        "fuel_type": 0,
        "id": 6,
        "model": "Mitsubishi Outlander",
        "note": null,
        "passenger_count": "2",
        "r_package": 2,
        "r_state": 1,
        "rating_date": "0, 0",
        "ratings": 0.0,
        "transmission": 0,
        "trim_edition": "",
        "updated_at": "Mon, 27 Mar 2023 14:07:57 GMT",
        "vehicle_type": 9,
        "w_package": 1,
        "w_state": 1
    },
    {
        "c_state": 0,
        "cover": "https://viptravels.lk/public/images/gallery/model-covers/shuttle.jpg",
        "created_at": "Mon, 27 Mar 2023 12:50:18 GMT",
        "deleted_at": null,
        "display_vehicle_type": "Sedan Car",
        "engine_capacity": 1000,
        "fuel_type": 0,
        "id": 20,
        "model": "Honda Shuttle",
        "note": null,
        "passenger_count": "3",
        "r_package": 4,
        "r_state": 1,
        "rating_date": "0, 0",
        "ratings": 0.0,
        "transmission": 0,
        "trim_edition": "",
        "updated_at": "Mon, 27 Mar 2023 14:02:31 GMT",
        "vehicle_type": 3,
        "w_package": 2,
        "w_state": 0
    },
    {
        "c_state": 0,
        "cover": "https://viptravels.lk/public/images/gallery/model-covers/inside.jpg",
        "created_at": "Mon, 27 Mar 2023 12:41:35 GMT",
        "deleted_at": null,
        "display_vehicle_type": "Sedan Car",
        "engine_capacity": 1000,
        "fuel_type": 0,
        "id": 19,
        "model": "Toyota Inside",
        "note": null,
        "passenger_count": "3",
        "r_package": 4,
        "r_state": 1,
        "rating_date": "0, 0",
        "ratings": 0.0,
        "transmission": 0,
        "trim_edition": "",
        "updated_at": "Mon, 27 Mar 2023 14:01:07 GMT",
        "vehicle_type": 3,
        "w_package": 2,
        "w_state": 0
    },
    {
        "c_state": 0,
        "cover": "https://viptravels.lk/public/images/gallery/model-covers/nissanmarch.jpg",
        "created_at": "Mon, 27 Mar 2023 09:02:21 GMT",
        "deleted_at": null,
        "display_vehicle_type": "Hatchback",
        "engine_capacity": 800,
        "fuel_type": 0,
        "id": 16,
        "model": "Nissan March",
        "note": null,
        "passenger_count": "4",
        "r_package": 1,
        "r_state": 1,
        "rating_date": "0, 0",
        "ratings": 0.0,
        "transmission": 0,
        "trim_edition": "",
        "updated_at": "Mon, 27 Mar 2023 11:03:51 GMT",
        "vehicle_type": 10,
        "w_package": 2,
        "w_state": 0
    },
    {
        "c_state": 0,
        "cover": "https://viptravels.lk/public/images/gallery/model-covers/suzukispecia.jpg",
        "created_at": "Mon, 27 Mar 2023 09:00:17 GMT",
        "deleted_at": null,
        "display_vehicle_type": "Hatchback",
        "engine_capacity": 1000,
        "fuel_type": 0,
        "id": 15,
        "model": "Suzuki Specia",
        "note": null,
        "passenger_count": "4",
        "r_package": 1,
        "r_state": 1,
        "rating_date": "0, 0",
        "ratings": 0.0,
        "transmission": 0,
        "trim_edition": "",
        "updated_at": "Mon, 27 Mar 2023 11:03:50 GMT",
        "vehicle_type": 10,
        "w_package": 2,
        "w_state": 0
    },
    {
        "c_state": 0,
        "cover": "https://viptravels.lk/public/images/gallery/model-covers/toyotaaqua.jpg",
        "created_at": "Mon, 27 Mar 2023 08:57:33 GMT",
        "deleted_at": null,
        "display_vehicle_type": "Hatchback",
        "engine_capacity": 1000,
        "fuel_type": 0,
        "id": 13,
        "model": "Toyota Aqua",
        "note": null,
        "passenger_count": "4",
        "r_package": 1,
        "r_state": 1,
        "rating_date": "0, 0",
        "ratings": 0.0,
        "transmission": 0,
        "trim_edition": "",
        "updated_at": "Mon, 27 Mar 2023 11:03:49 GMT",
        "vehicle_type": 10,
        "w_package": 2,
        "w_state": 0
    },
    {
        "c_state": 0,
        "cover": "https://viptravels.lk/public/images/gallery/model-covers/suzukialto.jpg",
        "created_at": "Mon, 27 Mar 2023 08:59:08 GMT",
        "deleted_at": null,
        "display_vehicle_type": "Hatchback",
        "engine_capacity": 800,
        "fuel_type": 0,
        "id": 14,
        "model": "Suzuki Alto",
        "note": null,
        "passenger_count": "4",
        "r_package": 1,
        "r_state": 1,
        "rating_date": "0, 0",
        "ratings": 0.0,
        "transmission": 0,
        "trim_edition": "",
        "updated_at": "Mon, 27 Mar 2023 11:03:49 GMT",
        "vehicle_type": 10,
        "w_package": 2,
        "w_state": 0
    },
    {
        "c_state": 0,
        "cover": "https://viptravels.lk/public/images/gallery/model-covers/wagonr.jpg",
        "created_at": "Mon, 27 Mar 2023 08:56:00 GMT",
        "deleted_at": null,
        "display_vehicle_type": "Hatchback",
        "engine_capacity": 1000,
        "fuel_type": 0,
        "id": 11,
        "model": "Wagon R",
        "note": null,
        "passenger_count": "4",
        "r_package": 1,
        "r_state": 1,
        "rating_date": "0, 0",
        "ratings": 0.0,
        "transmission": 0,
        "trim_edition": "",
        "updated_at": "Mon, 27 Mar 2023 11:03:48 GMT",
        "vehicle_type": 10,
        "w_package": 2,
        "w_state": 0
    },
    {
        "c_state": 0,
        "cover": "https://viptravels.lk/public/images/gallery/model-covers/hondafit.jpg",
        "created_at": "Mon, 27 Mar 2023 08:56:43 GMT",
        "deleted_at": null,
        "display_vehicle_type": "Hatchback",
        "engine_capacity": 1000,
        "fuel_type": 0,
        "id": 12,
        "model": "Honda Fit",
        "note": null,
        "passenger_count": "4",
        "r_package": 1,
        "r_state": 1,
        "rating_date": "0, 0",
        "ratings": 0.0,
        "transmission": 0,
        "trim_edition": "",
        "updated_at": "Mon, 27 Mar 2023 11:03:48 GMT",
        "vehicle_type": 10,
        "w_package": 2,
        "w_state": 0
    },
    {
        "c_state": 0,
        "cover": "https://viptravels.lk/public/images/gallery/model-covers/prado120.jpg",
        "created_at": "Mon, 27 Mar 2023 08:24:28 GMT",
        "deleted_at": null,
        "display_vehicle_type": "Luxury",
        "engine_capacity": 3956,
        "fuel_type": 1,
        "id": 10,
        "model": "Toyota Prado 120",
        "note": null,
        "passenger_count": "4",
        "r_package": 3,
        "r_state": 1,
        "rating_date": "0, 0",
        "ratings": 0.0,
        "transmission": 0,
        "trim_edition": "",
        "updated_at": "Mon, 27 Mar 2023 08:53:28 GMT",
        "vehicle_type": 12,
        "w_package": 1,
        "w_state": 0
    },
    {
        "c_state": 0,
        "cover": "https://viptravels.lk/public/images/gallery/model-covers/jaguarxtype.jpg",
        "created_at": "Mon, 27 Mar 2023 08:21:49 GMT",
        "deleted_at": null,
        "display_vehicle_type": "Luxury",
        "engine_capacity": 2099,
        "fuel_type": 0,
        "id": 9,
        "model": "Jaguar X-Type",
        "note": null,
        "passenger_count": "4",
        "r_package": 3,
        "r_state": 1,
        "rating_date": "0, 0",
        "ratings": 0.0,
        "transmission": 0,
        "trim_edition": "",
        "updated_at": "Mon, 27 Mar 2023 08:53:27 GMT",
        "vehicle_type": 12,
        "w_package": 1,
        "w_state": 0
    },
    {
        "c_state": 0,
        "cover": "https://viptravels.lk/public/images/gallery/model-covers/navara.jpg",
        "created_at": "Mon, 27 Mar 2023 07:12:18 GMT",
        "deleted_at": null,
        "display_vehicle_type": "SUV",
        "engine_capacity": 2488,
        "fuel_type": 0,
        "id": 7,
        "model": "Navara",
        "note": null,
        "passenger_count": "2",
        "r_package": 2,
        "r_state": 1,
        "rating_date": "0, 0",
        "ratings": 0.0,
        "transmission": 0,
        "trim_edition": "",
        "updated_at": "Mon, 27 Mar 2023 07:12:18 GMT",
        "vehicle_type": 9,
        "w_package": 2,
        "w_state": 0
    },
    {
        "c_state": 0,
        "cover": "https://viptravels.lk/public/images/gallery/model-covers/vezel.jpg",
        "created_at": "Mon, 27 Mar 2023 06:38:21 GMT",
        "deleted_at": null,
        "display_vehicle_type": "SUV",
        "engine_capacity": 1496,
        "fuel_type": 0,
        "id": 5,
        "model": "Vezel",
        "note": null,
        "passenger_count": "2",
        "r_package": 2,
        "r_state": 1,
        "rating_date": "0, 0",
        "ratings": 0.0,
        "transmission": 0,
        "trim_edition": "",
        "updated_at": "Mon, 27 Mar 2023 06:38:21 GMT",
        "vehicle_type": 9,
        "w_package": 2,
        "w_state": 1
    },
    {
        "c_state": 0,
        "cover": "https://viptravels.lk/public/images/gallery/model-covers/bmwx3.jpg",
        "created_at": "Mon, 27 Mar 2023 06:16:37 GMT",
        "deleted_at": null,
        "display_vehicle_type": "SUV",
        "engine_capacity": 1995,
        "fuel_type": 0,
        "id": 4,
        "model": "BMW X3",
        "note": null,
        "passenger_count": "2",
        "r_package": 2,
        "r_state": 1,
        "rating_date": "0, 0",
        "ratings": 0.0,
        "transmission": 0,
        "trim_edition": "",
        "updated_at": "Mon, 27 Mar 2023 06:16:37 GMT",
        "vehicle_type": 9,
        "w_package": 1,
        "w_state": 0
    },
    {
        "c_state": 0,
        "cover": "https://viptravels.lk/public/images/gallery/model-covers/chr.jpg",
        "created_at": "Mon, 27 Mar 2023 05:53:11 GMT",
        "deleted_at": null,
        "display_vehicle_type": "SUV",
        "engine_capacity": 1496,
        "fuel_type": 0,
        "id": 3,
        "model": "CHR",
        "note": null,
        "passenger_count": "2",
        "r_package": 2,
        "r_state": 1,
        "rating_date": "0, 0",
        "ratings": 0.0,
        "transmission": 0,
        "trim_edition": "",
        "updated_at": "Mon, 27 Mar 2023 05:53:11 GMT",
        "vehicle_type": 9,
        "w_package": 2,
        "w_state": 1
    }
]